"""empty message

Revision ID: 509858f4e93b
Revises: 7a357b1c7a85
Create Date: 2021-04-29 12:59:17.223369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509858f4e93b'
down_revision = '7a357b1c7a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications_global',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications_global')
    # ### end Alembic commands ###
