"""empty message

Revision ID: 5f9c9b10a313
Revises: 509858f4e93b
Create Date: 2021-05-01 10:56:37.966885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9c9b10a313'
down_revision = '509858f4e93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote_info', sa.Column('show_raw_vote_on_expire', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote_info', 'show_raw_vote_on_expire')
    # ### end Alembic commands ###
