"""00 Initial migration.

Revision ID: 76da6266e88b
Revises: 
Create Date: 2022-01-21 15:04:40.254855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76da6266e88b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_body',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('head', sa.Integer(), nullable=False),
    sa.Column('msg_from', sa.Integer(), nullable=False),
    sa.Column('msg_to', sa.Integer(), nullable=False),
    sa.Column('msg_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_head',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.Integer(), nullable=True),
    sa.Column('second', sa.Integer(), nullable=True),
    sa.Column('first_alias', sa.Text(), nullable=True),
    sa.Column('second_alias', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enroll_candidates',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=5), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enroll_forms',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues_issues',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('stu_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues_types',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.Column('typename', sa.String(length=255), nullable=False),
    sa.Column('typevalue', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('duty_user', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications_global',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), server_default='', nullable=False),
    sa.Column('sex', sa.String(length=5), server_default='', nullable=False),
    sa.Column('faculty', sa.String(length=20), server_default='', nullable=False),
    sa.Column('stu_id', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('points', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postcard_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wx_openid', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('with_audio', sa.Integer(), nullable=True),
    sa.Column('with_img', sa.Integer(), nullable=True),
    sa.Column('dir_name', sa.String(length=33), nullable=True),
    sa.Column('crop', sa.Text(), nullable=True),
    sa.Column('display', sa.Boolean(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('liked_by', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postcard_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_interceptors',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startswith', sa.String(length=100), nullable=False),
    sa.Column('role_bits', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_groups',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_groups_members',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_bit', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('role_text', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_bit')
    )
    op.create_table('user_users',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role_bits', sa.Integer(), nullable=True),
    sa.Column('current_ip', sa.String(length=100), nullable=True),
    sa.Column('last_login_ip', sa.String(length=100), nullable=True),
    sa.Column('last_login_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('objid', sa.String(length=100), nullable=True),
    sa.Column('validation_code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('vol_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('sex', sa.String(length=5), nullable=False),
    sa.Column('faculty', sa.String(length=20), nullable=False),
    sa.Column('stu_id', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('activity_name', sa.String(length=50), nullable=False),
    sa.Column('activity_faculty', sa.String(length=20), nullable=False),
    sa.Column('team', sa.String(length=50), nullable=False),
    sa.Column('activity_date_str', sa.String(length=30), nullable=False),
    sa.Column('activity_DATE', sa.DATE(), nullable=False),
    sa.Column('duty_person', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vol_time_edit',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vol_time_id', sa.Integer(), nullable=False),
    sa.Column('name_ori', sa.String(length=20), nullable=False),
    sa.Column('stu_id_ori', sa.BigInteger(), nullable=False),
    sa.Column('name_new', sa.String(length=20), nullable=False),
    sa.Column('stu_id_new', sa.BigInteger(), nullable=False),
    sa.Column('edit_by', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vol_time_old',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('sex', sa.String(length=5), nullable=False),
    sa.Column('faculty', sa.String(length=5), nullable=False),
    sa.Column('stu_id', sa.String(length=20), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('activity_name', sa.Text(), nullable=False),
    sa.Column('activity_faculty', sa.Text(), nullable=False),
    sa.Column('team', sa.Text(), nullable=False),
    sa.Column('activity_time', sa.Text(), nullable=False),
    sa.Column('duty_person', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voltime_dupname',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('dupNum', sa.SmallInteger(), nullable=False),
    sa.Column('edit_by', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote_candidates',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action_at', sa.Text(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote_info',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vote_min', sa.Integer(), nullable=False),
    sa.Column('vote_max', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Text(), nullable=False),
    sa.Column('shuffle', sa.Boolean(), nullable=False),
    sa.Column('is_poll', sa.Boolean(), nullable=False),
    sa.Column('show_stats', sa.Boolean(), nullable=True),
    sa.Column('show_raw_vote_on_expire', sa.Boolean(), nullable=True),
    sa.Column('show_raw_vote_on_voted', sa.Boolean(), nullable=True),
    sa.Column('title_label', sa.String(length=255), nullable=True),
    sa.Column('subtitle_label', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote_voters',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=100), nullable=False),
    sa.Column('candidate', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postcard_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wxid', sa.String(length=65), nullable=True),
    sa.Column('wx_name', sa.String(length=100), nullable=True),
    sa.Column('last_ip', sa.String(length=100), nullable=False),
    sa.Column('log_time', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('cards_saved', sa.Text(), nullable=True),
    sa.Column('avt_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['postcard_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postcard_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_user', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('with_audio', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['upload_user'], ['postcard_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postcard_templates')
    op.drop_table('postcard_users')
    op.drop_table('vote_voters')
    op.drop_table('vote_info')
    op.drop_table('vote_candidates')
    op.drop_table('voltime_dupname')
    op.drop_table('vol_time_old')
    op.drop_table('vol_time_edit')
    op.drop_table('vol_time')
    op.drop_table('user_users')
    op.drop_table('user_roles')
    op.drop_table('user_groups_members')
    op.drop_table('user_groups')
    op.drop_table('route_interceptors')
    op.drop_table('postcard_roles')
    op.drop_table('postcard_cards')
    op.drop_table('points')
    op.drop_table('notifications_global')
    op.drop_table('issues_types')
    op.drop_table('issues_issues')
    op.drop_table('enroll_forms')
    op.drop_table('enroll_candidates')
    op.drop_table('chat_head')
    op.drop_table('chat_body')
    # ### end Alembic commands ###
