"""empty message

Revision ID: 7a357b1c7a85
Revises: bef23d7bb010
Create Date: 2021-04-27 23:30:25.152349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a357b1c7a85'
down_revision = 'bef23d7bb010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote_candidates', 'subtitle_label')
    op.drop_column('vote_candidates', 'title_label')
    op.add_column('vote_info', sa.Column('subtitle_label', sa.Text(), nullable=True))
    op.add_column('vote_info', sa.Column('title_label', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote_info', 'title_label')
    op.drop_column('vote_info', 'subtitle_label')
    op.add_column('vote_candidates', sa.Column('title_label', sa.VARCHAR(length=255), nullable=True))
    op.add_column('vote_candidates', sa.Column('subtitle_label', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
