"""empty message

Revision ID: bef23d7bb010
Revises: dc48d70c9105
Create Date: 2021-04-27 22:58:03.997278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef23d7bb010'
down_revision = 'dc48d70c9105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_body',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('head', sa.Integer(), nullable=False),
    sa.Column('msg_from', sa.Integer(), nullable=False),
    sa.Column('msg_to', sa.Integer(), nullable=False),
    sa.Column('msg_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_head',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vote_candidates', sa.Column('subtitle_label', sa.Text(), nullable=True))
    op.add_column('vote_candidates', sa.Column('title_label', sa.String(length=255), nullable=True))
    op.add_column('vote_info', sa.Column('show_stats', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote_info', 'show_stats')
    op.drop_column('vote_candidates', 'title_label')
    op.drop_column('vote_candidates', 'subtitle_label')
    op.drop_table('chat_head')
    op.drop_table('chat_body')
    # ### end Alembic commands ###
