"""empty message

Revision ID: eba47c7e88af
Revises: e829ec17502d
Create Date: 2021-05-29 16:18:02.297705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba47c7e88af'
down_revision = 'e829ec17502d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_head', sa.Column('first_alias', sa.Text(), nullable=True))
    op.add_column('chat_head', sa.Column('second_alias', sa.Text(), nullable=True))
    op.add_column('enroll_forms', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enroll_forms', 'image')
    op.drop_column('chat_head', 'second_alias')
    op.drop_column('chat_head', 'first_alias')
    # ### end Alembic commands ###
