"""empty message

Revision ID: fbfa588ae967
Revises: 8d8899b6306c
Create Date: 2021-05-26 18:33:05.869392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbfa588ae967'
down_revision = '8d8899b6306c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications_global', sa.Column('path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications_global', 'path')
    # ### end Alembic commands ###
